name: snes9x-qt
base: core24
version: '1.63'
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]
summary: A Super Nintendo emulator
description: |
  Snes9x is a portable, freeware Super Nintendo Entertainment System (SNES) emulator.
  It basically allows you to play most games designed for the SNES and Super Famicom Nintendo game systems on your PC or Workstation; which includes some real gems that were only ever released in Japan.
grade: stable
confinement: strict
compression: lzo

apps:
  snes9x-qt:
    command-chain:
      - snap/command-chain/gpu-2404-wrapper
      - snap/command-chain/desktop-launch6
    command: usr/bin/snes9x-qt
    desktop: usr/gui/snes9x-emulator.desktop
    common-id: com.snes9x.Snes9x
    environment:
      SNAP_DESKTOP_RUNTIME: $SNAP/kf6
      GTK_USE_PORTAL: "1"
      QT_VERSION: "6"
      QT_QPA_PLATFORM: xcb
      QT_QPA_PLATFORMTHEME: xdgdesktopportal
      LD_LIBRARY_PATH: $SNAP/lxqt-support/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$LD_LIBRARY_PATH
      QT_PLUGIN_PATH: $SNAP/lxqt-support/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt6/plugins:$QT_PLUGIN_PATH
    plugs:
      - desktop
      - desktop-legacy
      - unity7
      - opengl
      - wayland
      - x11
      - screen-inhibit-control
      - audio-playback
      - network
      - network-bind
      - home
      - removable-media
      - mount-observe
      - joystick
      - bluez
      - udisks2

hooks:
  configure:
    command-chain:
      - snap/command-chain/hooks-configure-desktop

plugs:
  desktop:
    mount-host-font-cache: false
  gtk-2-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
  kf6-core24:
    content: kf6-core24-all
    interface: content
    target: $SNAP/kf6
    default-provider: kf6-core24
  gpu-2404:
    interface: content
    target: $SNAP/gpu-2404
    default-provider: mesa-2404
  shared-memory:
    private: true
  lxqt-support:
    content: lxqt-support
    interface: content
    target: $SNAP/lxqt-support
    default-provider: lxqt-support

layout:
  /usr/share/X11:
    symlink: $SNAP/kf6/usr/share/X11
  /usr/share/qt6:
    symlink: $SNAP/kf6/usr/share/qt6
  /usr/share/libdrm:
    bind: $SNAP/gpu-2404/libdrm
  /usr/share/drirc.d:
    symlink: $SNAP/gpu-2404/drirc.d
  /etc/fonts:
    bind: $SNAP/etc/fonts
  /usr/share/color-schemes:
    symlink: $SNAP/lxqt-support/usr/share/color-schemes
  /usr/share/Kvantum:
    symlink: $SNAP/lxqt-support/usr/share/Kvantum

package-repositories:
  - type: apt
    url: http://origin.archive.neon.kde.org/user
    suites: [noble]
    components: [main]
    architectures: [amd64, arm64]
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D

parts:
  snes9x:
    plugin: cmake
    source: https://github.com/snes9xgit/snes9x.git
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    source-subdir: qt
    build-snaps:
      - kde-qt6-core24-sdk
      - kf6-core24-sdk
    build-packages:
      - libsdl2-dev
      - libpng-dev
      - gettext
    build-environment:
      - PATH: /snap/kde-qt6-core24-sdk/current/usr/bin:/snap/kf6-core24-sdk/current/usr/bin${PATH:+:$PATH}
      - XDG_DATA_DIRS: $CRAFT_STAGE/usr/share:/snap/kde-qt6-core24-sdk/current/usr/share:/snap/kf6-core24-sdk/current/usr/share:/usr/share${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}
      - XDG_CONFIG_HOME: $CRAFT_STAGE/etc/xdg:/snap/kde-qt6-core24-sdk/current/etc/xdg:/snap/kf6-core24-sdk/current/etc/xdg:/etc/xdg${XDG_CONFIG_HOME:+:$XDG_CONFIG_HOME}
      - LD_LIBRARY_PATH: /snap/kde-qt6-core24-sdk/current/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}:/snap/kde-qt6-core24-sdk/current/usr/lib:/snap/kf6-core24-sdk/current/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}:/snap/kf6-core24-sdk/current/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/blas:/snap/kf6-core24-sdk/current/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/lapack:/snap/kf6-core24-sdk/current/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libproxy:/snap/kf6-core24-sdk/current/usr/lib:$CRAFT_STAGE/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}:$CRAFT_STAGE/usr/lib:$CRAFT_STAGE/lib/${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
      - CMAKE_PREFIX_PATH: $CRAFT_STAGE;/snap/kde-qt6-core24-sdk/current;/snap/kf6-core24-sdk/current;/usr${CMAKE_PREFIX_PATH:+;$CMAKE_PREFIX_PATH}
      - CMAKE_FIND_ROOT_PATH: $CRAFT_STAGE;/snap/kde-qt6-core24-sdk/current;/snap/kf6-core24-sdk/current;/usr${CMAKE_FIND_ROOT_PATH:+;$CMAKE_FIND_ROOT_PATH}
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr

  dependencies:
    plugin: nil
    stage-packages:
      - libsdl2-2.0-0
      - libdecor-0-0
    prime:
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libSDL2-2.0.so*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libdecor-0.so*

  launcher:
    after: [snes9x]
    plugin: nil
    source: ./launcher
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/gui
      mv -f snes9x-emulator.desktop $CRAFT_PART_INSTALL/usr/gui/
      mv -f snes9x.svg $CRAFT_PART_INSTALL/usr/gui/
    prime:
      - usr/gui

  command-chain:
    after: [launcher]
    plugin: nil
    source: ./launcher
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/snap
      cp -r command-chain $CRAFT_PART_INSTALL/snap/
      chmod 777 $CRAFT_PART_INSTALL/snap/command-chain/*