name: snes9x-qt
base: core24
version: '1.63'
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]
summary: A Super Nintendo emulator
description: |
  Snes9x is a portable, freeware Super Nintendo Entertainment System (SNES) emulator.
  It basically allows you to play most games designed for the SNES and Super Famicom Nintendo game systems on your PC or Workstation; which includes some real gems that were only ever released in Japan.
grade: stable
confinement: strict

apps:
  snes9x-qt:
    command: usr/bin/snes9x-qt
    desktop: usr/gui/snes9x-emulator.desktop
    common-id: com.snes9x.Snes9x
    environment:
      QT_QPA_PLATFORMTHEME: xdgdesktopportal
      LD_LIBRARY_PATH: $SNAP/lxqt-support/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$LD_LIBRARY_PATH
      QT_PLUGIN_PATH: $SNAP/lxqt-support/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt6/plugins:$QT_PLUGIN_PATH
    extensions: [kde-neon-6]
    plugs:
      - unity7
      - screen-inhibit-control
      - audio-playback
      - network
      - network-bind
      - home
      - removable-media
      - mount-observe
      - joystick
      - bluez

plugs:
  shared-memory:
    private: true
  lxqt-support:
    content: lxqt-support
    interface: content
    target: $SNAP/lxqt-support
    default-provider: lxqt-support

layout:
  /usr/share/color-schemes:
    symlink: $SNAP/lxqt-support/usr/share/color-schemes
  /usr/share/Kvantum:
    symlink: $SNAP/lxqt-support/usr/share/Kvantum

parts:
  snes9x:
    plugin: cmake
    source: https://github.com/snes9xgit/snes9x.git
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    source-subdir: qt
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
    build-packages:
      - libsdl2-dev
      - libpng-dev
      - gettext

  dependencies:
    plugin: nil
    stage-packages:
      - libsdl2-2.0-0
      - libdecor-0-0
    prime:
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libSDL2-2.0.so*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libdecor-0.so*

  launcher:
    after: [snes9x]
    plugin: nil
    source: ./launcher
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/gui
      mv -f snes9x-emulator.desktop $CRAFT_PART_INSTALL/usr/gui/
      mv -f snes9x.svg $CRAFT_PART_INSTALL/usr/gui/
    prime:
      - usr/gui
